management:
  endpoints:
    web:
      expose: health, info, metrics

  #security:
  #  ignored: /h2-console/**

server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  session:
    timeout: "600" # 10 minutes

spring:
  application:
    name: insurance
  datasource:
    platform: h2
    initialization-mode=: always
    url: jdbc:h2:mem:insurancedb
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.jdbc.time_zone: UTC
  h2:
    console:
      path: /h2-console
      enabled: true
  jackson:
    date-format: dd/MM/YYYY

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
