management:
  endpoints:
    web:
      expose: health, info, metrics

security:
  ignored: /h2-console/**
  
server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  session:
    timeout: "600" # 10 minutes

spring:
  application:
    name: insurance
  datasource:
    platform: h2
  jpa:
    generate-ddl: true
    properties:
      hibernate.jdbc.time_zone: UTC

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
